version: '3'

services:
  nginx:
    image: nginx:
  database:
    image: postgres:11.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: xxxxxx
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /Volumes/Life/Learning/codingNLearning/postgres:/var/lib/postgresql/data/pgdata
    networks:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend
      - frontend


  frontend:
    build:
      context: /Volumes/Life/Learning/codingNLearning/au-asw/asw-docker/react-app-01
      dockerfile: Dockerfile-frontend
    ports:
      - 1500:3000
    networks:
      - frontend

networks:
  backend:
  frontend:
