version: '3'

services:
  nginx:
    image: nginx:1.15.12
    hostname: reverse
    ports:
      - 4545:4545
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend

  database:
    image: postgres:11.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: xxxxxx
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-cache:/var/lib/postgresql/data/pgdata
    networks:
      - backend
      
  backend:
    build:
      context: ./dockerDemo
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend
      - frontend


  frontend:
    build:
      context: ./react-app-01
      dockerfile: Dockerfile-frontend
    ports:
      - 1500:3000
    networks:
      - frontend

networks:
  backend:
  frontend:
volumes: 
  db-cache:
