# 使用node版本11.12.0
FROM node:11.12.0

WORKDIR /code
# 将当前内容 放入code文件夹
ADD . /code

# 执行指令
RUN yarn install && yarn build && npm install -g http-server

# 暴露容器端口 8080
EXPOSE 3000

# 当执行docker run的时候会执行以下shell 脚本。
CMD http-server ./build -p 3000
